function Energy = InputF(time,Sprint,Endurance,Resistance,Ex_start,Amp) 

 Energy=(Sprint*Amp*((time > Ex_start)*(time < Ex_start+0.5)+(time > Ex_start+4.5)*(time < Ex_start+5)+(time > Ex_start+9)*(time < Ex_start+9.5)))...
 +(Endurance*Amp*(time > Ex_start)*(time < Ex_start+90)) ...
 +(Resistance*Amp*((time > Ex_start)*(time < Ex_start+0.5)+(time > Ex_start+2.5)*(time < Ex_start+3)+(time > Ex_start+5)*(time < Ex_start+5.5)+ ...
 (time > Ex_start+7.5)*(time < Ex_start+8)+(time > Ex_start+10)*(time < Ex_start+10.5)+(time > Ex_start+12.5)*(time < Ex_start+13)));